-- Optional sample data so the search page has something to show during
-- development. Safe to skip entirely, and safe to delete once real
-- organizations are on the platform:
--
--   DELETE FROM partners WHERE Email LIKE '%@example.org';
--
-- These are fictional orgs with example.org addresses -- not real contacts.

INSERT INTO partners (Name, OrganizationType, Expertise, Resources, Email, PhoneNumber, Location, Bio) VALUES
('Coders Over Borders', 'Non-profit', 'Web Development', 'Volunteer developers, Free website builds', 'hello@codersoverborders.example.org', '555-0142', 'Austin, TX', 'We build free websites and internal tools for small nonprofits that cannot afford an agency. Looking for orgs who need a site and can offer us community reach.'),
('Riverside Tech', 'Small Business', 'Software Engineering', 'Student internships, Mentorship hours, Meeting space', 'partnerships@riversidetech.example.org', '555-0198', 'Austin, TX', 'A 40-person software shop that wants to give local students real engineering experience. We can host interns and offer mentors.'),
('Green Earth Initiative', 'NGO', 'Environmental Advocacy', 'Volunteer network, Community outreach', 'connect@greenearth.example.org', '555-0173', 'Portland, OR', 'Environmental nonprofit with 800 active volunteers. We need event space and legal help; we offer manpower for community projects.'),
('Lakeside Community Centre', 'Community Org', 'Community Programming', 'Event space, Commercial kitchen, Weekend venue', 'bookings@lakesidecc.example.org', '555-0119', 'Portland, OR', 'Neighborhood center with a 200-person hall and a commercial kitchen sitting empty most weekends. Happy to host partner events in exchange for programming.'),
('Studio Meridian', 'Design Studio', 'Brand & Design', 'Pro-bono branding, Logo design, Print collateral', 'studio@meridian.example.org', '555-0166', 'Chicago, IL', 'Small design studio that takes on two pro-bono nonprofit rebrands a year. We are looking for causes our team cares about.'),
('APEERS', 'Non-profit', 'Youth Mentorship', 'Youth audience, Volunteer mentors, After-school programs', 'team@apeers.example.org', '555-0155', 'Chicago, IL', 'Peer mentorship program serving 300 high school students. We need branding help and funding; we offer access to a youth audience.'),
('Northgate Legal Aid', 'Non-profit', 'Legal Services', 'Pro-bono legal advice, Nonprofit filings, Contract review', 'intake@northgatelegal.example.org', '555-0187', 'Boston, MA', 'We handle incorporation, 501(c)(3) filings, and contract review for small nonprofits at no cost. We need help with our own outreach and website.'),
('Bright Path Tutoring', 'Small Business', 'Education', 'Tutoring hours, Curriculum design, Test prep', 'info@brightpath.example.org', '555-0134', 'Boston, MA', 'Tutoring company donating 200 hours a year to community programs. Looking for youth organizations that can connect us with students who need it.'),
('Harvest Table', 'Non-profit', 'Food Security', 'Food distribution, Warehouse space, Refrigerated transport', 'ops@harvesttable.example.org', '555-0121', 'Denver, CO', 'Regional food bank with warehouse capacity and refrigerated trucks. We need volunteer coordination software and marketing support.'),
('Summit Marketing Co.', 'Small Business', 'Marketing', 'Social media strategy, Campaign design, Copywriting', 'hello@summitmarketing.example.org', '555-0148', 'Denver, CO', 'Boutique marketing agency that donates campaign work to one local cause per quarter. We want partners doing visible community work.'),
('Cedar Valley Arts Collective', 'Community Org', 'Arts Programming', 'Gallery space, Teaching artists, Workshop facilitation', 'hello@cedarvalleyarts.example.org', '555-0192', 'Nashville, TN', 'Artist collective with gallery space and teaching artists. We need grant writing help and can offer venue space and workshops in return.'),
('Openline Consulting', 'Consulting Firm', 'Grant Writing', 'Grant writing, Fundraising strategy, Board training', 'contact@openline.example.org', '555-0107', 'Nashville, TN', 'We help small nonprofits build fundraising programs. We need introductions to organizations that are ready to grow, and design help for our materials.');
