"""partnerships table

Revision ID: 0c0fe819780f
Revises: 3a29bff9ef63
Create Date: 2026-08-06 18:12:14.932188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c0fe819780f'
down_revision: Union[str, Sequence[str], None] = '3a29bff9ef63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnerships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('proposer_gives', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('recipient_gives', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('timeline', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'withdrawn')", name='ck_partnerships_status'),
    sa.CheckConstraint('proposer_id <> recipient_id', name='ck_partnerships_not_self'),
    sa.ForeignKeyConstraint(['proposer_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index('ix_partnerships_proposer', 'partnerships', ['proposer_id'], unique=False)
    op.create_index('ix_partnerships_recipient', 'partnerships', ['recipient_id'], unique=False)
    op.create_index('uq_partnerships_one_pending', 'partnerships', ['proposer_id', 'recipient_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_partnerships_one_pending', table_name='partnerships', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_partnerships_recipient', table_name='partnerships')
    op.drop_index('ix_partnerships_proposer', table_name='partnerships')
    op.drop_table('partnerships')
    # ### end Alembic commands ###
