"""organizations table replacing users/partners/onboarding_profiles

Revision ID: 3a29bff9ef63
Revises: 
Create Date: 2026-08-06 17:55:30.277248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a29bff9ef63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote_friendly', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('needs', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('offers', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('needs_note', sa.Text(), nullable=True),
    sa.Column('offers_note', sa.Text(), nullable=True),
    sa.Column('partnership_goals', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_organizations_needs', 'organizations', ['needs'], unique=False, postgresql_using='gin')
    op.create_index('ix_organizations_offers', 'organizations', ['offers'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_offers', table_name='organizations', postgresql_using='gin')
    op.drop_index('ix_organizations_needs', table_name='organizations', postgresql_using='gin')
    op.drop_table('organizations')
    # ### end Alembic commands ###
