"""is_demo flag on organizations

Revision ID: 3a43be51bdf7
Revises: 0c0fe819780f
Create Date: 2026-08-07 01:40:02.405770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a43be51bdf7'
down_revision: Union[str, Sequence[str], None] = '0c0fe819780f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_demo')
    # ### end Alembic commands ###
