"""email verification fields on organizations

Revision ID: 402773cae456
Revises: 3a43be51bdf7
Create Date: 2026-08-11 11:57:15.385203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402773cae456'
down_revision: Union[str, Sequence[str], None] = '3a43be51bdf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('organizations', sa.Column('email_verify_token', sa.String(length=64), nullable=True))
    op.add_column('organizations', sa.Column('email_verify_sent_at', sa.DateTime(timezone=True), nullable=True))
    # Named explicitly -- autogenerate left this unnamed, which Postgres would
    # accept on create but which op.drop_constraint(None, ...) cannot target.
    op.create_unique_constraint(
        'uq_organizations_email_verify_token', 'organizations', ['email_verify_token']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_organizations_email_verify_token', 'organizations', type_='unique'
    )
    op.drop_column('organizations', 'email_verify_sent_at')
    op.drop_column('organizations', 'email_verify_token')
    op.drop_column('organizations', 'email_verified')
    # ### end Alembic commands ###
