"""links_public opt-in flag on organizations

Revision ID: 5442f60f1196
Revises: b9561890464c
Create Date: 2026-08-11 16:24:57.981024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5442f60f1196'
down_revision: Union[str, Sequence[str], None] = 'b9561890464c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('links_public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'links_public')
    # ### end Alembic commands ###
