"""email notifications preference on organizations

Revision ID: 6aadf53f4dae
Revises: 5442f60f1196
Create Date: 2026-08-11 20:56:00.000331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aadf53f4dae'
down_revision: Union[str, Sequence[str], None] = '5442f60f1196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('email_notifications', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'email_notifications')
    # ### end Alembic commands ###
