"""saved leads table

Revision ID: 8f447045fa88
Revises: 7a9959e052c0
Create Date: 2026-08-15 12:38:27.305152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f447045fa88'
down_revision: Union[str, Sequence[str], None] = '7a9959e052c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('saved_organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('organization_id <> saved_organization_id', name='ck_saved_leads_not_self'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'saved_organization_id', name='uq_saved_leads_pair')
    )
    op.create_index('ix_saved_leads_organization', 'saved_leads', ['organization_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_leads_organization', table_name='saved_leads')
    op.drop_table('saved_leads')
    # ### end Alembic commands ###
