"""profile views table

Revision ID: a0623ef93f4f
Revises: 8f447045fa88
Create Date: 2026-08-15 13:09:30.751016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0623ef93f4f'
down_revision: Union[str, Sequence[str], None] = '8f447045fa88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('viewer_key', sa.String(length=64), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profile_views_dedup', 'profile_views', ['organization_id', 'viewer_key', 'viewed_at'], unique=False)
    op.create_index('ix_profile_views_org_seen', 'profile_views', ['organization_id', 'viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_views_org_seen', table_name='profile_views')
    op.drop_index('ix_profile_views_dedup', table_name='profile_views')
    op.drop_table('profile_views')
    # ### end Alembic commands ###
