"""profile link fields on organizations

Revision ID: b9561890464c
Revises: 402773cae456
Create Date: 2026-08-11 15:11:59.330430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9561890464c'
down_revision: Union[str, Sequence[str], None] = '402773cae456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('website_url', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('instagram_url', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('x_url', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'linkedin_url')
    op.drop_column('organizations', 'x_url')
    op.drop_column('organizations', 'instagram_url')
    op.drop_column('organizations', 'website_url')
    # ### end Alembic commands ###
