"""note on saved leads

Revision ID: ce31fc6e6110
Revises: 6fb0c815318b
Create Date: 2026-08-18 11:46:18.355784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce31fc6e6110'
down_revision: Union[str, Sequence[str], None] = '6fb0c815318b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_leads', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_leads', 'note')
    # ### end Alembic commands ###
