"""password reset token fields on organizations

Revision ID: d4841b79d2bf
Revises: 55c59219492b
Create Date: 2026-08-12 12:07:24.709867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4841b79d2bf'
down_revision: Union[str, Sequence[str], None] = '55c59219492b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('password_reset_token', sa.String(length=64), nullable=True))
    op.add_column('organizations', sa.Column('password_reset_sent_at', sa.DateTime(timezone=True), nullable=True))
    # Named explicitly -- autogenerate left this unnamed, which Postgres would
    # accept on create but which op.drop_constraint(None, ...) cannot target.
    op.create_unique_constraint(
        'uq_organizations_password_reset_token', 'organizations', ['password_reset_token']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_organizations_password_reset_token', 'organizations', type_='unique'
    )
    op.drop_column('organizations', 'password_reset_sent_at')
    op.drop_column('organizations', 'password_reset_token')
    # ### end Alembic commands ###
